# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_trajectory_controller
    - gripper_position_controller

  arm_trajectory_controller:
    type: FollowJointTrajectory
    joints:
      - base_link__link1
      - link1__link2
      - link2__link3
      - link3__link4
      - link4__link5
      - link5__link6
    action_ns: follow_joint_trajectory
    default: true
  gripper_position_controller:
    type: FollowJointTrajectory
    joints:
      - finger_right_joint
    action_ns: follow_joint_trajectory
    default: true