controller_manager:
  ros__parameters:
    update_rate: 100 #Hz
    use_sim_time: true

    arm_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_position_controller:
      type: position_controllers/GripperActionController
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_trajectory_controller:
  ros__parameters:
    joints:
      - base_link__link1
      - link1__link2
      - link2__link3
      - link3__link4
      - link4__link5
      - link5__link6
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

gripper_position_controller:
  ros__parameters:
    action_monitor_rate: 20.0
    allow_stalling: true
    goal_tolerance: 0.01
    joint: 'finger_right_joint'
    max_effort: 100.0
    stall_timeout: 3.0
    stall_velocity_threshold: 0.001